/**
 * The Help panel's question corpus: what each kind of reader should get first for a question, or "no match" (null)
 * where the portal has no answer. A list means any of those entries answers it for that reader (the first place
 * among close matches goes to what the reader can use, so two entries can both be right). Kept apart from the test
 * so a script can run the same table against another copy of src/lib/help.
 *
 * Sources: the questions of both help reviews' probes, every question tests/help.test.ts asks, and questions a
 * first-time visitor, team member, judge and organizer ask about timing (when does X open or close), where to do
 * something and who can see what. Each expectation was checked against the entry's answer and the page it names.
 */

export type Reader = "visitor" | "participant" | "judge" | "organizer" | "admin";
export type Want = string | null | (string | null)[];
export type CorpusRow = [question: string, want: Want | ({ all: Want } & Partial<Record<Reader, Want>>)];

export const READERS: Record<Reader, { signedIn: boolean; roles: ("participant" | "judge" | "organizer" | "admin")[] }> = {
  visitor: { signedIn: false, roles: [] },
  participant: { signedIn: true, roles: ["participant"] },
  judge: { signedIn: true, roles: ["judge"] },
  organizer: { signedIn: true, roles: ["organizer"] },
  admin: { signedIn: true, roles: ["admin"] },
};

const ORG = { organizer: "settings", admin: "settings" } as const;

export const CORPUS: CorpusRow[] = [
  // ---- timing: when does something open or close ----
  ["when does judging end", "judging-close"],
  ["what time does judging close", "judging-close"],
  ["when does judging start", ["judging-close", "about"]],
  ["how do i end judging", { all: "judging-close", organizer: ["judging-close", "publish"], admin: ["judging-close", "publish"] }],
  ["how do i set the judging close time", "judging-close"],
  ["when do submissions close", { all: ["hand-in", "about"], organizer: ["hand-in", "about", "settings"], admin: ["hand-in", "about", "settings"] }],
  ["when does submission close", { all: ["hand-in", "about"], organizer: ["hand-in", "about", "settings"], admin: ["hand-in", "about", "settings"] }],
  ["submissions close", { all: ["hand-in", "about"], organizer: ["hand-in", "about", "settings"], admin: ["hand-in", "about", "settings"] }],
  ["when can i submit until", { all: ["hand-in", "about"], organizer: ["hand-in", "about", "settings"], admin: ["hand-in", "about", "settings"] }],
  ["when is the submission deadline", { all: ["hand-in", "about"], organizer: ["hand-in", "about", "settings"], admin: ["hand-in", "about", "settings"] }],
  ["submission deadline", { all: ["hand-in", "about"], organizer: ["hand-in", "about", "settings"], admin: ["hand-in", "about", "settings"] }],
  ["what is the deadline", ["about", "hand-in"]],
  ["when is the deadline", "about"],
  ["can i submit late", { all: "hand-in", organizer: ["hand-in", "submissions", "team-organizer"], admin: ["hand-in", "submissions", "team-organizer"] }],
  ["when can i edit my project", "hand-in"],
  ["how do i close submissions", { all: ["settings", "about", "hand-in"], organizer: ["settings", "about"], admin: ["settings", "about"] }],
  ["how do i reopen submissions", { all: ["settings", "about", "hand-in"], organizer: ["settings", "about"], admin: ["settings", "about"] }],
  ["how do i extend submissions", { all: ["settings", "about", "hand-in"], organizer: ["settings", "about"], admin: ["settings", "about"] }],
  ["how do i change the deadline", { all: ["settings", "about", "hand-in"], organizer: ["settings", "about"], admin: ["settings", "about"] }],
  ["how do i extend the deadline", { all: ["settings", "about", "hand-in"], organizer: ["settings", "about"], admin: ["settings", "about"] }],
  ["how do i change the submission deadline", { all: ["settings", "about", "hand-in"], organizer: ["settings", "about"], admin: ["settings", "about"] }],
  ["where do i set the deadline", { all: ["about", "settings"], organizer: ["settings", "about"], admin: ["settings", "about"] }],
  ["how do i change the dates", { all: ["about", "settings"], ...ORG }],
  ["when does voting close", { all: ["vote", "about", "vote-hidden"], organizer: ["voting-tab", "vote", "about"], admin: ["voting-tab", "vote", "about"] }],
  ["when does voting open", { all: ["vote", "about"], organizer: ["voting-tab", "vote", "about"], admin: ["voting-tab", "vote", "about"] }],
  ["until when can i vote", { all: ["vote", "about"], organizer: ["voting-tab", "vote", "about"], admin: ["voting-tab", "vote", "about"] }],
  ["how long is voting open", { all: ["vote", "about"], organizer: ["voting-tab", "vote", "about"], admin: ["voting-tab", "vote", "about"] }],
  ["when can i vote", { all: ["vote", "about"], organizer: ["vote", "about", "voting-tab"], admin: ["vote", "about", "voting-tab"] }],
  ["how do i open voting", { all: ["voting-tab", "about"], organizer: "voting-tab", admin: "voting-tab" }],
  ["how do i close voting", { all: ["voting-tab", "about"], organizer: "voting-tab", admin: "voting-tab" }],
  ["when are results out", ["results-public", "publish"]],
  ["when do results come out", ["results-public", "publish"]],
  ["when are results published", ["publish", "results-public"]],
  ["when is the event", ["about", "events"]],
  ["timeline", ["about", "judging-close"]],
  ["what time zone are the dates in", "about"],
  ["how long is the hackathon", "about"],
  ["when can i see the votes", { all: ["vote-hidden", "about"], organizer: ["voting-tab", "vote-hidden"], admin: ["voting-tab", "vote-hidden"] }],

  // ---- where to do something ----
  ["how do i score a project", { all: ["how-scored", "judge-console"], judge: "judge-console" }],
  ["where do i score", { all: ["judge-console", "how-scored"], judge: "judge-console" }],
  ["how do i score", { all: ["how-scored", "judge-console"], judge: "judge-console" }],
  ["how do i rate a project", "judge-console"],
  ["how do i edit a score", { all: ["judge-console", "freeze"], judge: "judge-console" }],
  ["can i change my score", { all: "judge-console", participant: ["judge-console", "my-feedback"] }],
  ["where is the judge console", "judge-console"],
  ["where do i see my batch", "judge-console"],
  ["how many projects do i judge", { all: "reviews-per-project", judge: ["judge-console", "reviews-per-project"] }],
  ["how many projects do i have to judge", { all: "reviews-per-project", judge: ["judge-console", "reviews-per-project"] }],
  ["how do i skip a project", "conflict"],
  ["where do i declare a conflict", "conflict"],
  ["declare conflict of interest", "conflict"],
  ["can i judge my own project", { all: ["assignment", "conflict"], judge: "conflict" }],
  ["keyboard shortcuts for judging", "judge-keys"],
  ["which is better left or right", "pairwise-compare"],
  ["where do i vote", { all: "vote", organizer: ["vote", "voting-tab"], admin: ["vote", "voting-tab"] }],
  ["how do i vote", "vote"],
  ["how many projects can i vote for", "vote"],
  ["can i vote for my own team", "vote"],
  ["where do i hand in", "hand-in"],
  ["how do i submit my project", "hand-in"],
  ["how to hand in", "hand-in"],
  ["can i edit my submission", "hand-in"],
  ["how do i edit my submission", "hand-in"],
  ["can i edit my project after submitting", "hand-in"],
  ["how do i take part", ["my-project", "hand-in"]],
  ["where is my team", "teams"],
  ["how do i add a teammate", "teams"],
  ["invite teammates", "teams"],
  ["how do i join a team", "teams"],
  ["how do i leave my team", "teams"],
  ["how many people per team", "teams"],
  ["change the team name", { all: "teams", organizer: ["teams", "team-organizer"], admin: ["teams", "team-organizer"] }],
  ["how do i leave a comment", "comments"],
  ["where do i see the results", "results-public"],
  ["where are the results", "results-public"],
  ["who won", "results-public"],
  ["how do i see my score", { all: ["my-feedback", "my-project"], judge: "judge-console" }],
  ["where is my feedback", { all: ["my-feedback", "my-project"] }],
  ["my feedback from the judges", "my-feedback"],
  ["where are my reviews", { all: ["my-feedback", "my-project"], judge: "judge-console" }],
  ["how did my team do", ["my-feedback", "my-project"]],
  ["where do i find my certificate", { all: ["certificate", "verify"], judge: ["certificate", "judge-record"], organizer: ["issue-records", "certificate"], admin: ["issue-records", "certificate"] }],
  ["how do i verify a certificate", "verify"],
  ["check a certificate is real", "verify"],
  ["issue certificates", "issue-records"],
  ["where do i invite judges", "invite-judges"],
  ["how do i invite judges", "invite-judges"],
  ["invite judges", "invite-judges"],
  ["how do i add a judge", "invite-judges"],
  ["how do i join as a judge", { all: "judge-invite", organizer: ["judge-invite", "invite-judges"], admin: ["judge-invite", "invite-judges"] }],
  ["i got a judge invite", { all: "judge-invite", organizer: ["judge-invite", "invite-judges"], admin: ["judge-invite", "invite-judges"] }],
  ["how do i accept a judge invite", "judge-invite"],
  ["how do i remove a judge", "remove-judge"],
  ["remove a judge who accepted by mistake", "remove-judge"],
  ["where do i change the rubric", "weights"],
  ["how do i change the rubric", "weights"],
  ["change rubric weights", "weights"],
  ["how do i change the rubric weights", "weights"],
  ["how do i add tracks", ["settings", "tracks"]],
  ["how do i add prizes", ["settings", "about"]],
  ["where is settings", "settings"],
  ["how do i see all submissions", { all: ["gallery", "submissions"], organizer: "submissions", admin: "submissions" }],
  ["how do i see the audit log", "audit-tab"],
  ["audit log", "audit-tab"],
  ["what is the audit log", "audit-tab"],
  ["how do i download the csv", "exports"],
  ["download csv", "exports"],
  ["where do i export scores", "exports"],
  ["how do i export results", "exports"],
  ["how do i publish results", "publish"],
  ["how publish", "publish"],
  ["where do i see votes", { all: ["vote-hidden", "voting-tab"], organizer: "voting-tab", admin: "voting-tab" }],
  ["how do i create an event", "new-event"],
  ["create a new event", "new-event"],
  ["how do i add a co-organizer", "co-organizers"],
  ["add a co-organiser", "co-organizers"],
  ["how do i become an organizer", "become-organizer"],
  ["how do i get organizer access", "become-organizer"],
  ["make me an organizer", "become-organizer"],
  ["how do i switch to pairwise", "switch-pairwise"],
  ["switch to pairwise", "switch-pairwise"],
  ["how do i import fixtures", "imports"],
  ["import fixtures.json", "imports"],
  ["how do i embed the gallery", "embed"],
  ["embed the gallery on our website", "embed"],
  ["set up a webhook", "webhooks"],
  ["api token", "api-tokens"],
  ["how do i make an api token", "api-tokens"],
  ["rest api docs", "api-docs"],
  ["is there an api", "api"],
  ["how do i back up the database", "backups"],
  ["how do i back up the portal", "backups"],
  ["how do i run it with docker", "run-it"],
  ["docker compose up", "run-it"],
  ["merge duplicate project", "duplicates"],
  ["project with only one review", "under-reviewed"],
  ["how are projects assigned to judges", "assignment"],
  ["settle the decisions", "decisions"],
  ["override a judge with a reason", "exclude-judge"],
  ["reinstate the flat judge", "flat-judge"],

  // ---- accounts ----
  ["how do i sign in", "sign-in"],
  ["how do i log in", "sign-in"],
  ["login", "sign-in"],
  ["how do i sign up", "sign-up"],
  ["how do i sign out", "sign-out"],
  ["how do i log out", "sign-out"],
  ["how do i switch accounts", "sign-out"],
  ["where is the logout button", "sign-out"],
  ["change password", "change-password"],
  ["how do i change my password", "change-password"],
  ["reset password", { all: ["change-password", "accounts"], admin: "accounts" }],
  ["i forgot my password", { all: "change-password", admin: ["accounts", "change-password"] }],
  ["forgot my password", { all: ["change-password", "accounts"], admin: ["accounts", "change-password"] }],
  ["how do i reset someone's password", "accounts"],

  // ---- who can see what ----
  ["who can see my scores", { all: ["other-judges", "my-feedback", "results-public"], judge: "other-judges" }],
  ["can judges see each other's scores", "other-judges"],
  ["can i see other judges scores", "other-judges"],
  ["who can see my email", "privacy"],
  ["who can see my feedback", "my-feedback"],
  ["can participants see scores", ["my-feedback", "results-public"]],
  ["who can see my project", ["project-page", "gallery"]],
  ["can other teams see my project", ["project-page", "gallery"]],
  ["who can see the votes", { all: "vote-hidden", organizer: ["voting-tab", "vote-hidden"], admin: ["voting-tab", "vote-hidden"] }],
  ["who sees the vote count", { all: "vote-hidden", organizer: ["voting-tab", "vote-hidden"], admin: ["voting-tab", "vote-hidden"] }],
  ["who can see the audit log", "audit-tab"],
  ["who can see the results before publishing", ["publish", "results-organizer", "results-public", "freeze"]],
  ["is my data safe", "privacy"],
  ["what data do you keep about me", "privacy"],
  ["is my activity tracked", "privacy"],
  ["how do i delete my account", "privacy"],
  ["can i delete my account", "privacy"],

  // ---- how it works ----
  ["how are projects scored", "how-scored"],
  ["how is the score calculated", "how-scored"],
  ["how does scoring work", { all: "how-scored", judge: ["how-scored", "judge-console"] }],
  ["how does judging work", { all: "how-scored", judge: ["how-scored", "judge-console"] }],
  ["how are winners chosen", ["how-scored", "results-public"]],
  ["how many judges per project", "reviews-per-project"],
  ["who decides the number of judges per project", "reviews-per-project"],
  ["what is normalization", "leniency"],
  ["how are scores normalized", "leniency"],
  ["what is leniency", "leniency"],
  ["what does leniency mean", "leniency"],
  ["strict judges vs generous judges", "leniency"],
  ["what does the plus minus mean", "plus-minus"],
  ["what is the plus minus", "plus-minus"],
  ["what does ± mean next to the score", "plus-minus"],
  ["who scored 4 4 4", "flat-judge"],
  ["why was a judge left out", "flat-judge"],
  ["what is the flat judge rule", "flat-judge"],
  ["is it random", "signal-check"],
  ["is the ranking just random", "signal-check"],
  ["what is the permutation share", "signal-check"],
  ["what does the signal check mean", "signal-check"],
  ["is the ranking fair", ["leniency", "signal-check"]],
  ["what is pairwise", { all: "pairwise", judge: ["pairwise-compare", "pairwise"], organizer: ["switch-pairwise", "pairwise"], admin: ["switch-pairwise", "pairwise"] }],
  ["what is pairwise mode", { all: "pairwise", organizer: ["pairwise", "switch-pairwise"], admin: ["pairwise", "switch-pairwise"] }],
  ["bradley terry", "pairwise"],
  ["what is a ballot", "ballots"],
  ["open link votes", "open-link"],
  ["what is the head hash", "audit-chain"],
  ["can results be changed after publishing", "freeze"],
  ["unpublish results", "freeze"],
  ["judge ledger", "judge-ledger"],
  ["ranking so far", "ranking-so-far"],
  ["why did my rank change", { all: ["ranking-so-far", "leniency"], judge: "ranking-so-far" }],
  ["what is the rubric", ["about", "weights", "settings"]],
  ["what is a track", "tracks"],
  ["what tracks are there", "tracks"],
  ["what is a category", "tracks"],
  ["what are the prizes", { all: "about", organizer: ["about", "settings"], admin: ["about", "settings"] }],
  ["about the event", ["about", "events"]],
  ["what is demo mode", "demo-mode"],
  ["demo mode checker sessions", "demo-mode"],
  ["dark mode", "mode"],
  ["too many requests 429", "rate-limits"],
  ["why do i get 403", "refusals"],

  // ---- no answer in the portal ----
  ["how do i contact the organizers", null],
  ["can i change my email", null],
  ["can i change my email address", null],
  ["how do i change my email", null],
  ["how do i change my name", null],
  ["can i rename my account", null],
  ["can i pay with a credit card", null],
  ["is there a mobile app", null],
  ["who won last year", null],
  ["can two teams merge", null],
  ["how do i report a bug", null],
  ["where do i upload slides", null],
  ["can i submit a video", null],
  ["what is the wifi password", null],
  ["where is the venue", null],
  ["is lunch provided", null],
  ["how do i get a refund", null],
  ["banana bread recipe", null],
  ["how do i disqualify a project", null],
  ["how do i delete a project", "teams"],
  ["can judges see my name", ["privacy", null]],
  ["is my draft visible", ["hand-in", "my-project", null]],
  ["how do i upload images", ["hand-in", "my-project", null]],
  ["how do i verify the results", ["results-public", "results-organizer", "audit-chain", "verify"]],
  ["what is this portal", ["events", "about", "run-it", null]],
  ["where are my scores", { all: ["my-feedback", "my-project"], judge: "judge-console" }],
];
